using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProgrammeringsProv_SebastianW
{
    class Bocker
    {

        public int price; //int som heter price

        public string name = "";
        public string GetName()
        {
            return name; //returnerar name så att ifall den var private kunde den användas inom main.
        }

        public string kategory = "";
        



    }


    
}
